import 'dart:async';

import 'package:floor/floor.dart';
import 'package:solo_leveling/features/community/data/models/colleague_relation.dart';
import 'package:solo_leveling/features/community/data/models/comment.dart';
import 'package:solo_leveling/features/community/data/models/xp_investment.dart';
import 'package:solo_leveling/global_data/converters/date_time_converter.dart';
import 'package:solo_leveling/global_data/database/colleague_relation_dao.dart';
import 'package:solo_leveling/global_data/database/comment_dao.dart';
import 'package:solo_leveling/global_data/database/xp_investment_dao.dart';
import 'package:solo_leveling/global_data/models/enums.dart';
import 'package:sqflite/sqflite.dart' as sqflite;
// import 'package:path/path.dart' as path;
import '../models/user.dart';
import '../models/quest_history.dart';
import '../models/leaderboard_entry.dart';
import 'user_dao.dart';
import 'quest_history_dao.dart';
import 'leaderboard_dao.dart';

part 'app_database.g.dart'; // Generated by Floor


@TypeConverters([DateTimeConverter])
@Database(
  version: 1, 
  entities: [User, QuestHistory, Comment, LeaderboardEntry, ColleagueRelation, XpInvestment],
  // typeConverters: [DateTimeConverter], // Register the class
)
abstract class AppDatabase extends FloorDatabase {
  UserDao get userDao;
  QuestHistoryDao get questHistoryDao;
  LeaderboardDao get leaderboardDao;
  CommentDao get commentDao; // Assuming you have a CommentDao defined
  ColleagueRelationDao get colleagueRelationDao;
  XpInvestmentDao get xpInvestmentDao;
}

// Add this function
Future<AppDatabase> getDatabase() async {
  final database = await $FloorAppDatabase.databaseBuilder(
    'solo_leveling_app.db', // Database file name
  ).build();
  return database;
}